name: mascdb
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - abseil-cpp=20210324.2=h9c3ff4c_0
  - alabaster=0.7.12=py_0
  - alsa-lib=1.2.3=h516909a_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argh=0.26.2=pyh9f0ad1d_1002
  - argon2-cffi=20.1.0=py38h497a2fe_2
  - arrow=1.1.1=pyhd8ed1ab_0
  - arrow-cpp=5.0.0=py38h4026a5f_3_cpu
  - asciitree=0.3.3=py_2
  - astroid=2.7.3=py38h578d9bd_0
  - async_generator=1.10=py_0
  - atomicwrites=1.4.0=pyh9f0ad1d_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - autopep8=1.5.7=pyhd8ed1ab_0
  - aws-c-cal=0.5.11=h95a6274_0
  - aws-c-common=0.6.2=h7f98852_0
  - aws-c-event-stream=0.2.7=h3541f99_13
  - aws-c-io=0.10.5=hfb6a706_0
  - aws-checksums=0.1.11=ha31a3da_7
  - aws-sdk-cpp=1.8.186=hb4091e7_3
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - binaryornot=0.4.4=py_1
  - black=21.8b0=pyhd8ed1ab_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - bokeh=2.3.3=py38h578d9bd_0
  - bottleneck=1.3.2=py38h6c62de6_4
  - brotlipy=0.7.0=py38h497a2fe_1001
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.17.2=h7f98852_0
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py38h578d9bd_0
  - cffi=1.14.6=py38ha65f79e_0
  - cftime=1.5.0=py38hb5d20a5_0
  - chardet=4.0.0=py38h578d9bd_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=8.0.1=py38h578d9bd_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cookiecutter=1.7.3=pyh6c4a22f_0
  - cryptography=3.4.7=py38ha5dfef3_0
  - curl=7.78.0=hea6ffbf_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py38h497a2fe_3
  - dask=2021.8.1=pyhd8ed1ab_0
  - dask-core=2021.8.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.6=h48d8840_2
  - debugpy=1.4.1=py38h709712a_0
  - decorator=5.0.9=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - diff-match-patch=20200713=pyh9f0ad1d_0
  - distributed=2021.8.1=py38h578d9bd_0
  - docutils=0.17.1=py38h578d9bd_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - enum34=1.1.10=py38h32f6830_2
  - expat=2.4.1=h9c3ff4c_0
  - fasteners=0.16=pyhd8ed1ab_0
  - flake8=3.9.2=pyhd8ed1ab_0
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h0708190_1
  - fsspec=2021.8.1=pyhd8ed1ab_0
  - gettext=0.19.8.1=h0b5b191_1005
  - gflags=2.2.2=he1b5a44_1004
  - glib=2.68.4=h9c3ff4c_0
  - glib-tools=2.68.4=h9c3ff4c_0
  - glog=0.5.0=h48cff8f_0
  - grpc-cpp=1.39.1=hf1f433d_0
  - gst-plugins-base=1.18.4=hf529b03_2
  - gstreamer=1.18.4=h76c114f_2
  - hdf4=4.2.15=h10796ff_3
  - hdf5=1.12.1=nompi_h2750804_100
  - heapdict=1.0.1=py_0
  - icu=68.1=h58526e2_0
  - idna=3.1=pyhd3deb0d_0
  - imagecodecs-lite=2019.12.3=py38h5c078b8_3
  - imageio=2.9.0=py_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=4.8.1=py38h578d9bd_0
  - importlib_metadata=4.8.1=hd8ed1ab_0
  - inflection=0.5.1=pyh9f0ad1d_0
  - intervaltree=3.0.2=py_0
  - ipykernel=6.3.1=py38he5a9106_0
  - ipython=7.27.0=py38he5a9106_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.4=pyhd8ed1ab_0
  - isort=5.9.3=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.0=py38h578d9bd_2
  - jeepney=0.7.1=pyhd8ed1ab_0
  - jinja2=2.11.3=pyh44b312d_0
  - jinja2-time=0.2.0=py_2
  - jpeg=9d=h36c2ea0_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter=1.0.0=py38h578d9bd_6
  - jupyter_client=7.0.2=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py38h578d9bd_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.1=pyhd8ed1ab_0
  - keyring=23.1.0=py38h578d9bd_0
  - kiwisolver=1.3.2=py38h1fd1430_0
  - krb5=1.19.2=hcc1bbae_0
  - lazy-object-proxy=1.6.0=py38h497a2fe_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=11_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_5
  - libbrotlidec=1.0.9=h7f98852_5
  - libbrotlienc=1.0.9=h7f98852_5
  - libcblas=3.9.0=11_linux64_openblas
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.78.0=h2574ce0_0
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=hcdb4288_3
  - libffi=3.3=h58526e2_2
  - libgcc-ng=11.1.0=hc902ee8_8
  - libgfortran-ng=11.1.0=h69a702a_8
  - libgfortran5=11.1.0=h6c583b3_8
  - libglib=2.68.4=h3e27bee_0
  - libgomp=11.1.0=hc902ee8_8
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=11_linux64_openblas
  - libllvm11=11.1.0=hf817b99_2
  - libnetcdf=4.8.1=nompi_hb3fd0d9_101
  - libnghttp2=1.43.0=h812cca2_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.3=hd57d9b9_0
  - libprotobuf=3.16.0=h780b84a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libspatialindex=1.9.3=h9c3ff4c_4
  - libssh2=1.10.0=ha56f1ee_0
  - libstdcxx-ng=11.1.0=h56837e0_8
  - libthrift=0.14.2=he6d91bd_1
  - libtiff=4.3.0=hf544144_1
  - libutf8proc=2.6.1=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1003
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzip=1.8.0=h4de3113_0
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=1.1.1=py38h497a2fe_3
  - matplotlib=3.4.3=py38h578d9bd_0
  - matplotlib-base=3.4.3=py38hf4fb855_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py38h497a2fe_1004
  - monotonic=1.5=py_0
  - msgpack-python=1.0.2=py38h1fd1430_1
  - mypy_extensions=0.4.3=py38h578d9bd_3
  - mysql-common=8.0.25=ha770c72_2
  - mysql-libs=8.0.25=hfa10184_2
  - nbclient=0.5.4=pyhd8ed1ab_0
  - nbconvert=6.1.0=py38h578d9bd_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - netcdf4=1.5.7=nompi_py38h2823cc8_102
  - networkx=2.3=py_0
  - notebook=6.4.3=pyha770c72_0
  - nspr=4.30=h9c3ff4c_0
  - nss=3.69=hb5efdd6_0
  - numcodecs=0.9.0=py38h709712a_0
  - numpy=1.21.2=py38he2449b9_0
  - numpydoc=1.1.0=py_1
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - orc=1.6.10=h58a87f1_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.2=py38h43a58ef_0
  - pandoc=2.14.2=h7f98852_0
  - pandocfilters=1.4.2=py_1
  - parquet-cpp=1.5.1=2
  - parso=0.8.2=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pathlib=1.0.1=py38h578d9bd_4
  - pathspec=0.9.0=pyhd8ed1ab_0
  - patsy=0.5.1=py_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.1=py38h8e6f84c_0
  - pip=21.2.4=pyhd8ed1ab_0
  - platformdirs=2.3.0=pyhd8ed1ab_0
  - pluggy=0.13.1=py38h578d9bd_4
  - pooch=1.5.1=pyhd8ed1ab_0
  - poyo=0.5.0=py_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - prompt_toolkit=3.0.20=hd8ed1ab_0
  - psutil=5.8.0=py38h497a2fe_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyarrow=5.0.0=py38h1bc9799_3_cpu
  - pycodestyle=2.7.0=pyhd8ed1ab_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydocstyle=6.1.1=pyhd8ed1ab_0
  - pyflakes=2.3.1=pyhd8ed1ab_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - pylint=2.10.2=pyhd8ed1ab_0
  - pyls-spyder=0.4.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py38h578d9bd_7
  - pyqt-impl=5.12.3=py38h7400c14_7
  - pyqt5-sip=4.19.18=py38h709712a_7
  - pyqtchart=5.12=py38h7400c14_7
  - pyqtwebengine=5.12.1=py38h7400c14_7
  - pyrsistent=0.17.3=py38h497a2fe_2
  - pysocks=1.7.1=py38h578d9bd_3
  - python=3.8.10=h49503c6_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-lsp-black=1.0.0=pyhd8ed1ab_0
  - python-lsp-jsonrpc=1.0.0=pyhd8ed1ab_0
  - python-lsp-server=1.2.1=pyhd8ed1ab_0
  - python-slugify=5.0.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2021.1=pyhd8ed1ab_0
  - pywavelets=1.1.1=py38h6c62de6_3
  - pyxdg=0.27=pyhd8ed1ab_0
  - pyyaml=5.4.1=py38h497a2fe_1
  - pyzmq=22.2.1=py38h2035c66_0
  - qdarkstyle=3.0.2=pyhd8ed1ab_0
  - qstylizer=0.2.1=pyhd8ed1ab_0
  - qt=5.12.9=hda022c4_4
  - qtawesome=1.0.3=pyhd8ed1ab_0
  - qtconsole=5.1.1=pyhd8ed1ab_0
  - qtpy=1.10.0=pyhd8ed1ab_0
  - re2=2021.08.01=h9c3ff4c_0
  - readline=8.1=h46c0cb4_0
  - regex=2021.8.28=py38h497a2fe_0
  - requests=2.26.0=pyhd8ed1ab_0
  - rope=0.19.0=pyhd8ed1ab_0
  - rtree=0.9.7=py38h02d302b_2
  - s2n=1.0.10=h9b69904_0
  - scikit-image=0.18.3=py38h43a58ef_0
  - scipy=1.7.1=py38h56a6a73_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - secretstorage=3.3.1=py38h578d9bd_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=57.4.0=py38h578d9bd_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.8=he1b5a44_3
  - snowballstemmer=2.1.0=pyhd8ed1ab_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sphinx=4.1.2=pyh6c4a22f_1
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_0
  - spyder=5.1.1=py38h578d9bd_0
  - spyder-kernels=2.1.0=py38h578d9bd_0
  - sqlite=3.36.0=h9cd32fc_0
  - statsmodels=0.12.2=py38h5c078b8_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - terminado=0.11.1=py38h578d9bd_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - text-unidecode=1.3=py_0
  - textdistance=4.2.1=pyhd8ed1ab_0
  - three-merge=0.1.1=pyh9f0ad1d_0
  - tifffile=2019.7.26.2=py38_0
  - tinycss2=1.1.0=pyhd8ed1ab_0
  - tk=8.6.11=h21135ba_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=1.2.1=pyhd8ed1ab_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py38h497a2fe_1
  - traitlets=5.1.0=pyhd8ed1ab_0
  - typed-ast=1.4.3=py38h497a2fe_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - ujson=4.0.2=py38h709712a_0
  - unidecode=1.2.0=pyhd8ed1ab_0
  - urllib3=1.26.6=pyhd8ed1ab_0
  - watchdog=2.1.5=py38h578d9bd_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - widgetsnbextension=3.5.1=py38h578d9bd_4
  - wrapt=1.12.1=py38h497a2fe_3
  - wurlitzer=3.0.1=py38h578d9bd_0
  - xarray=0.19.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yapf=0.31.0=pyhd8ed1ab_0
  - zarr=2.9.5=pyhd8ed1ab_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zict=2.0.0=py_0
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h516909a_1010
  - zstd=1.5.0=ha95c52a_0
prefix: /home/grazioli/anaconda3/envs/mascdb
