name: build-doc-pymascdb
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - numpy
  - pandas
  - pyarrow
  - bottleneck
  - zarr
  - xarray
  - dask
  - distributed
  - matplotlib-base
  - seaborn
  - scikit-image
  - jupyter
  - pip
  - pre_commit
  - pandoc
  - nbsphinx==0.9.3
  - sphinx==7.2.6
  - sphinx-book-theme==1.1.0
  - sphinx-mdinclude==0.5.3
  - sphinx-gallery
  - docutils
